In [3]:
import pygame
from sys import exit
import numpy as np

pygame 2.6.1 (SDL 2.28.4, Python 3.13.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [3]:
pygame.init()

#creating surfaces
screen = pygame.display.set_mode((800,600))
pygame.display.set_caption("Avatar:Battle Field")
rock1 = pygame.image.load("rock.png")
rock2 = pygame.image.load("rock.png")
background = pygame.image.load("background.png")


clock = pygame.time.Clock()

#creating rock surfaces
radius = 10
rock1 = pygame.Surface((2*radius,2*radius),pygame.SRCALPHA)
pygame.draw.circle(rock1,"brown",(radius,radius),radius)
rock2 = pygame.Surface((2*radius,2*radius),pygame.SRCALPHA)
pygame.draw.circle(rock2,"brown",(radius,radius),radius)

#randomising x and y positions
x1 = np.random.choice(np.arange(100,700,1)) + radius
x2 = np.random.choice(np.arange(100,700,1)) + radius
y1 = np.random.choice(np.arange(100,500,1)) - radius
y2 = np.random.choice(np.arange(100,500,1)) - radius

#randomising x and y velocities
vx1 = np.random.choice(np.arange(-400,400,1)) 
vx2 = np.random.choice(np.arange(-400,400,1)) 
vy1 = np.random.choice(np.arange(-400,400,1)) 
vy2 = np.random.choice(np.arange(-400,400,1)) 

                      

#initialisg velocity and position
pos_rock1 = np.array([x1,y1])
pos_rock2 = np.array([x2,y2])

v_rock1 = np.array([vx1,vx2])
v_rock2 = np.array([vx2,vy2])



test_surface = pygame.Surface((100,200))


while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            exit()




            
    screen.blit(background,np.array([0,0]))
    screen.blit(rock1,(pos_rock1[0]-radius,pos_rock1[1]-radius))
    screen.blit(rock2,(pos_rock2[0]-radius,pos_rock2[1]-radius))
    

    
    pos_rock1 = pos_rock1 + v_rock1*clock.tick(60)/1000
    pos_rock2 = pos_rock2 + v_rock2*clock.tick(60)/1000
    
    

    rel_pos= pos_rock1 - pos_rock2
    distance = np.linalg.norm(rel_pos)

    if not 100+radius<=pos_rock1[0]<=700-radius:
        v_rock1[0] = v_rock1[0]*-1

    if not 100+radius<=pos_rock2[0]<=700-radius:
        v_rock2[0] = v_rock2[0]*-1

    if not 100+radius<=pos_rock1[1]<=500-radius:
        v_rock1[1] = v_rock1[1]* -1

    if not 100+radius<=pos_rock2[1]<=500-radius:
        v_rock2[1] = v_rock2[1]* -1
    
    
        

        
        

    
    pygame.display.update()
    clock.tick(60)

SystemExit: 

C:\Users\Cansv\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [4]:
def create_rocks(nmax,radius):
        rocks = []
        for i in range(0,nmax):
            #creating rock surface
            rock = pygame.Surface((2*radius,2*radius),pygame.SRCALPHA)
            pygame.draw.circle(rock,"brown",(radius,radius),radius)
            rocks.append(rock)
        return rocks

def posvel_rocks(nmax,radius):
    pos_x = []
    pos_y = []
    vel_x = []
    vel_y = []
    
    for n in range(0,nmax):  
        xp = np.random.choice(np.arange(100+radius,700-radius,1)) 
        yp = np.random.choice(np.arange(100+radius,500-radius,1)) 

        vx = np.random.choice(np.arange(-400,400,1))
        vy = np.random.choice(np.arange(-400,400,1))

        
        
        pos_x.append(xp)
        pos_y.append(yp)

        vel_x.append(vx)
        vel_y.append(vy)
    
    return np.array([pos_x,pos_y]),np.array([vel_x,vel_y])
    
    
pos, vel = posvel_rocks(2,10)

pos

print(pos)
print(vel)

pos+vel*0.5




[[561 674]
 [318 477]]
[[ -42 -108]
 [-383 -256]]


array([[540. , 620. ],
       [126.5, 349. ]])

In [11]:
pygame.init()

radius=10

#creating surfaces
screen = pygame.display.set_mode((800,600))
pygame.display.set_caption("Avatar:Battle Field")
background = pygame.image.load("background.png")

#generating rocks
rocks = create_rocks(10,10)


#generating positions and velocities
pos , vel = posvel_rocks(10,10)




clock = pygame.time.Clock()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            exit()
    
    screen.blit(background,np.array([0,0]))
    
    for rock,i in zip(rocks,range(len(rocks))):
        screen.blit(rock,(pos[0,i]-radius,pos[1,i]-radius))

    pos = pos +vel*clock.tick(60)/1000

    for x,v,i in zip(pos[0],vel[0],range(len(rocks))):
        if not 100+radius<=x<=700-radius:
            vel[0,i] = v *-1
    
    for y,v,i in zip(pos[1],vel[1],range(len(rocks))):
        if not 100+radius<=y<=500-radius:
            vel[1,i] = v *-1
    
            
        

    
    

    pygame.display.update()

SystemExit: 

In [7]:
pos , vel = posvel_rocks(2,10)

pos

pos_x, pos_y = pos



pos_x

pos_y

pos


array([[330, 498],
       [119, 331]])

In [20]:
 for rock,p in zip(rocks,pos):
        screen.blit(rock,(pos[0],pos[1]))
    

    for p,v in zip(pos,vel):
        p = p + v * clock.tick(60)/1000


    for i in pos:
        #horizontal condition
        if not 100+radius<=i[0]<=700-radius:
            i[0] = i[0]*-1

        #vertical condiiton
        if not 100+radius<=i[1]<=500-radius:
            i[1] = i[1]* -1
    

IndentationError: unindent does not match any outer indentation level (<string>, line 5)

In [ ]:
print(pos)

pos[0]

In [48]:
range(2)

for i in range(2):
    print(i)

0
1


In [27]:
a = np.array([1,2,3])
d = np.array([a,2,3,4])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [25]:
d[0]

np.int64(1)